# determinarea numelui si varstei cunoscutilor care-l "stiu" pe 
# Sir Tim Berners-Lee dupa reputatie si sunt examinati de profesori
# (un exemplu de utilizare a nodurilor blanc si a clauzei DISTINCT)

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rel: <http://purl.org/vocab/relationship/>
PREFIX s: <http://www.infoiasi.ro/wade/>

SELECT DISTINCT ?nume ?ani ?prof
WHERE {
   [ ] foaf:knows ?persoana .
   ?persoana foaf:firstName ?nume ;
             rel:knowsByReputation <http://www.w3.org/People/Berners-Lee/card#i> ;
             foaf:age ?ani .
   ?prof s:examineaza ?persoana
}