# recurgerea la filtrari bazate pe expresii regulate
# pentru a determina numele studentelor

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?numeStudenta
WHERE {
   ?persoana foaf:gen ?gen ;
             foaf:firstName ?numeStudenta .
   FILTER regex (?gen, "^female", "i") .
}