# informatii despre data de nastere a lui Eminescu
# printr-o interogare asupra DBpedia
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo:	<http://dbpedia.org/ontology/>
SELECT ?dataNastere 
WHERE { 
  ?persoana rdfs:label "Mihai Eminescu"@en ; 
            dbo:birthDate ?dataNastere . 
}