# Organizatiile comune participante la 2 evenimente,
# pe baza datelor RDF disponibile la adresa <http://data.semanticweb.org/>
# Ca punct terminal SPARQL se poate folosi <http://data.semanticweb.org/sparql>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX swrc: <http://swrc.ontoware.org/ontology#>

SELECT DISTINCT ?nume
FROM NAMED <http://data.semanticweb.org/conference/iswc/2011/complete>
FROM NAMED <http://data.semanticweb.org/conference/eswc/2010/complete>
WHERE {
   GRAPH ?g1 { 
     ?org a foaf:Organization ; 
          foaf:name ?nume
   }
   GRAPH ?g2 { 
     ?org a foaf:Organization ; 
          foaf:name ?nume
   }
   FILTER (?g1 != ?g2) .
}
LIMIT 3